### ISSUE TITLE
Neither link works

### ISSUE THREAD

**Issue by Zireael07** [jice-nospam/yendor.ts#11]

**Comment by jice-nospam** [comment]
Yeah, roguecentral.org is down, my hosting company shut it down without possibility to migrate to another server. I'll see if I can host directly the demo on github. Thanks for the report

**Comment by Zireael07** [comment]
Links don't go to a 404, though but to some fishy site with expired certs - even more reason to host demos on github.

**Comment by jice-nospam** [comment]
I removed the links from the readme. It's not a fishy site, it's another project of mine :)
