### ISSUE TITLE
CONSOLE_XXXX and DEFAULT_CONSOLE_XXXX consts not working properly

### ISSUE THREAD

**Issue by kn-f** [jice-nospam/yendor.ts#4]
Changing CONSOLE_WIDTH values just shows a black screen.
Same behavior when setting DEFAULT_CONSOLE_WIDTH in Umbra.
Using same or different values in both constants gives the same result: black screen.

Changing CONSOLE_HEIGHT const  and DEFAULT_CONSOLE_HEIGHTS show the screen but bars, messages and scroll are not working properly

**Comment by jice-nospam** [comment]
Works better by changing this line in main.ts :
app.run(engine, {consoleWidth: Constants.CONSOLE_WIDTH, consoleHeight: Constants.CONSOLE_HEIGHT});
but you'll have to delete the local storage with localStorage.clear()
thanks for the report
