### ISSUE TITLE
Transpilation Error

### ISSUE THREAD

**Issue by OlivierLamiraux** [jice-nospam/yendor.ts#6]
Look like SimpleNoise class have a new constructor, and get1D have an additional argument.

src/game/actor_light.ts(86,32): error TS2346: Supplied parameters do not match a
ny signature of call target.
src/game/actor_light.ts(89,21): error TS2346: Supplied parameters do not match a
ny signature of call target.
jake aborted.

**Comment by jice-nospam** [comment]
it should be fixed now. Note that you have to install uglify-js to be able to compile. The jake targets are now dev and prod instead of compile

**Comment by OlivierLamiraux** [comment]
Thank, see the commit a big bugfix :)
